#question_69:-
#given the code below ,use the correct method o9n line 3 in order to find out the number of elwments in my_tup.
my_tup = ("romania","poland","estonia","bulgaria","slovenia","hungary")
element = len(my_tup)
print(element)


# question_70:-
#given the code below ,use the correct method on line 3 in order to find out the index of slovakia in my_tup.
my_tup = ("romania","poland","estonia","bulgaria","slovakia","slovenia","hungary")
element =my_tup.index("slovakia")
print(element)

#question_71:-
#GIVEN THE CODE  BELOW ,WRITE CODE IN ORDER TO PERFROM TUPLE ASSIGNMENT ON LINE 3 AND OBTAIN THE RESULT BELOW.
my_tup =("Romania","poland","estonia")
(ro,po,es) = my_tup
print(ro+","+po+","+es)


#question_72:-
#given the code below , use the correct method on line 3 in order to find out the last elements of my_tup in alphabetical order.
my_tup=("romania","poland","estonia","bulgaria","slovakia","slovenia","hungary")
last = max(my_tup)
print(last)


#question_73-:
#given the code below , use the correct method on line 3 in order to find out the number of occurrences of estonia in my_tup.
my_tup = ("romania","poland","Estonia","bulgaria","slovakia","Estoina","romania","slovenia","hungary")
number = my_tup.count("Estonia")
print(number)






